version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=prod
      - DB_PATH=sqlite:///./app/core/database/data.db
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"