[project]
name = "backend-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "loguru>=0.7.3",
    "ruff>=0.12.0",
    "typing>=3.10.0.0",
    "uvicorn>=0.34.3",
]
