from typing import Protocol

from app.api.domains.blog_post.models.blog_post_models import BlogPost, BlogPostCreate, BlogPostPatch, BlogPostUpdate


class IBlogPostRepository(Protocol):
    def create_blog_post(self, blog_post: BlogPostCreate) -> BlogPost: ...
    def update_blog_post(self, post_id: int, blog_post: BlogPostUpdate) -> BlogPost: ...
    def patch_blog_post(self, post_id: int, blog_post: BlogPostPatch) -> BlogPost: ...
    def delete_blog_post(self, post_id: int) -> int: ...
    def get_blog_post(self, post_id: int) -> BlogPost: ...
    def get_all_blog_posts(self) -> list[BlogPost]: ...
